[package]
name = "godot-codegen"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"
license = "MPL-2.0"
keywords = ["gamedev", "godot", "engine", "codegen"]
categories = ["game-engines", "graphics"]

[features]
default = []
codegen-fmt = ["prettyplease", "syn"]
codegen-full = []
double-precision = []
custom-godot = ["godot-bindings/custom-godot"]

[dependencies]
godot-bindings = { path = "../godot-bindings" }
heck = "0.4"
nanoserde = "0.1.29"
proc-macro2 = "1"
quote = "1"
prettyplease = { version = "0.2.6", optional = true }
syn = { version = "2.0.18", features = ["full"], optional = true }

# Since we don't use Regex for unicode parsing, the features unicode-bool/unicode-gencat are used instead of unicode-perl.
# See also https://docs.rs/regex/latest/regex/#unicode-features.
regex = { version = "1.5.5", default-features = false, features = ["std", "unicode-bool", "unicode-gencat"] }
